version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  n8n:
    build: .
    depends_on:
      - postgres
    environment:
      # Web/UI
      PORT: 5555
      N8N_USER_FOLDER: /data
      N8N_PROTOCOL: http

      # Auth & security
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: password
      N8N_ENCRYPTION_KEY: please_change_me

      # Database (Postgres)
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n_password
      DB_POSTGRESDB_SCHEMA: public

    ports:
      - "5555:5555"
    volumes:
      - n8n_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  n8n_data:
